### ISSUE TITLE
Effect of actions on events in events.json

### ISSUE THREAD

**Issue by ShivaniH** [Pk13055/jeevan-khel#1]
https://github.com/Pk13055/jeevan-khel/blob/07868cf555e8d0704378f7a7dd33c9c2d7feddfa/config/db/events.json#L58

How do we specify that event 3's probability should be changed to 1 if this option is selected?

Should the events list (for an option) be something like this, instead of just "events": [3]  ?

"events": [ { 
                   "id": 3,
                   "probability": 1,
                   "phase": 3
                  } ]

**Comment by Pk13055** [comment]
Yeah basically, specify the ID as `3` and probability as `1`. No need to specify the phase since that remains unchanged, right?
